sources:
  - url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
    filename: adaway.txt
    output_format: hosts
  - url: https://raw.githubusercontent.com/StevenBlack/hosts/refs/heads/master/hosts
    filename: stevenblack.txt
  - url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
    filename: adguard.txt
    output_format: rfc1035

output_dir: ./testdata
interval_seconds: 30

http_client:
  timeout_seconds: 30

whitelist:
 - "google.com"
 - "*.domain.com"
 - "*.163.com"